Language: node_js
node_js:
  - 12.16.1

script:
- cd ./api-gateway
- npm install
- npm test
- cd ..
- cd ..
# - sudo ssh -i ./bora-bragantino.pem ec2-user@34.230.3.209
- ssh ec2-user@54.80.102.160 "mv -rf /home/new/bora-node /home/old/bora-node-old"
- exit
- scp -vp22 ./bora-node ec2-user@54.80.102.160:/home/new/
# - npm start
