Language: node_js
node_js:
  - 12.16.1

script:
- cd ./api-gateway
- npm install
- npm test
- cd ..
- cd ..
# - sudo ssh -i ./bora-bragantino.pem ec2-user@34.230.3.209
- ssh -i ec2-user@18.234.41.197 "mv /home/ec2-user/new/bora-node /home/ec2-user/old/bora-node-old"
# - yes | command-that-asks-for-input
- exit
- scp -vp22 ./bora-node ec2-user@18.234.41.197:/home/ec2-user/new/
# - npm start
