Language: node_js
node_js:
  - 12.16.1

notifications:
  email:
    - bgabriel.arruda@gmail.com

script:
- cd ./api-gateway
- npm install
- npm test
- cd ..
- sudo chmod 777 ./bora-node.pem
- 'which ssh-agent || ( apt-get install -qq openssh-client )'
- eval $(ssh-agent -s)
- sudo ssh -i ./bora-node.pem  ec2-user@3.233.168.122
# - scp -vp22 ./bora-node ec2-user@18.234.41.197:/home/ec2-user/new/
# - sudo ssh -i ./bora-bora-node.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@18.234.41.197
# - sudo scp -vp22 ./bora-node UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@18.234.41.197:/home/ec2-user/new/
# - ssh -i ec2-user@18.234.41.197 "mv /home/ec2-user/new/bora-node /home/ec2-user/old/bora-node-old"
-
# - exit
# - npm start
